/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventsApiController : ControllerBase
    { 
        /// <summary>
        /// Создание события фильма
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с фильмом</remarks>
        /// <param name="movieEvent">Данные события фильма</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/movie")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateMovieEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateMovieEvent([FromBody]MovieEvent movieEvent)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"partition\" : 0,\n  \"offset\" : 42,\n  \"event\" : {\n    \"payload\" : \"{}\",\n    \"id\" : \"movie-1-viewed\",\n    \"type\" : \"movie\",\n    \"timestamp\" : \"2023-01-15T14:30:00Z\"\n  },\n  \"status\" : \"success\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EventResponse>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Создание события платежа
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с платежом</remarks>
        /// <param name="paymentEvent">Данные события платежа</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/payment")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreatePaymentEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreatePaymentEvent([FromBody]PaymentEvent paymentEvent)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"partition\" : 0,\n  \"offset\" : 42,\n  \"event\" : {\n    \"payload\" : \"{}\",\n    \"id\" : \"movie-1-viewed\",\n    \"type\" : \"movie\",\n    \"timestamp\" : \"2023-01-15T14:30:00Z\"\n  },\n  \"status\" : \"success\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EventResponse>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Создание события пользователя
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с пользователем</remarks>
        /// <param name="userEvent">Данные события пользователя</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/user")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateUserEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateUserEvent([FromBody]UserEvent userEvent)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"partition\" : 0,\n  \"offset\" : 42,\n  \"event\" : {\n    \"payload\" : \"{}\",\n    \"id\" : \"movie-1-viewed\",\n    \"type\" : \"movie\",\n    \"timestamp\" : \"2023-01-15T14:30:00Z\"\n  },\n  \"status\" : \"success\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EventResponse>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
