/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;
using Microsoft.Extensions.Logging;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventsApiController : ControllerBase
    { 
        private readonly IKafkaEventPublisher _kafka;
        private readonly IKafkaEventReader _kafkaReader;
        private readonly ILogger<EventsApiController> _logger;


        // Конструктор для внедрения зависимостей
        public EventsApiController(
            IKafkaEventPublisher kafka,
            IKafkaEventReader kafkaReader,
            ILogger<EventsApiController> logger)
        {
            _kafka = kafka ?? throw new ArgumentNullException(nameof(kafka));
            _kafkaReader = kafkaReader ?? throw new ArgumentNullException(nameof(kafkaReader));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
    
        /// <summary>
        /// Создание события фильма
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с фильмом</remarks>
        /// <param name="movieEvent">Данные события фильма</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/movie")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateMovieEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateMovieEvent([FromBody]MovieEvent movieEvent)
        {

            movieEvent.Status = "success";
            return new ObjectResult(movieEvent)
                            {
                                StatusCode = 201
                            }; //Created($"/api/payments/{payment.Id}", payment);
        }

        /// <summary>
        /// Создание события платежа
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с платежом</remarks>
        /// <param name="paymentEvent">Данные события платежа</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/payment")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreatePaymentEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreatePaymentEvent([FromBody]PaymentEvent paymentEvent)
        {

            try
            {
                _logger.LogInformation("Entered CreatePayment");
                Console.WriteLine("=== 1 ===");

                // Генерируем уникальный ID платежа (в реальности — из БД или ID-сервиса)
                var paymentId = Random.Shared.Next(1000, 999999);
                var timestamp = DateTime.UtcNow;

            

                // Формируем событие платежа
                 paymentEvent = new PaymentEvent
                {
                    PaymentId = paymentId,
                    UserId = paymentEvent.UserId,
                    Amount = paymentEvent.Amount,
                    Status = "success",
                    Timestamp = timestamp
                };

                // Публикуем событие в Kafka
                var eventId = Guid.NewGuid().ToString();
                var @event = new Event
                {
                    Id = eventId,
                    Type = "payment",
                    Timestamp = timestamp,
                    Payload = paymentEvent
                };

                Console.WriteLine("=== 2 ===");
                var eventData = JsonConvert.SerializeObject(@event);
                _kafka.PublishAsync("payment-events", eventId, eventData);
               
                _logger.LogInformation("Published payment event: {EventId} for payment {PaymentId}", eventId, paymentId);
                _logger.LogInformation("й1");
                Console.WriteLine("=== 3 ===");
                
                return new ObjectResult(paymentEvent)
                            {
                                StatusCode = 201
                            }; //Created($"/api/payments/{payment.Id}", payment);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to create payment or publish event");
                return StatusCode(500, new Error {  VarError = "Internal Server Error" });
            }
        }

        /// <summary>
        /// Создание события пользователя
        /// </summary>
        /// <remarks>Регистрирует новое событие, связанное с пользователем</remarks>
        /// <param name="userEvent">Данные события пользователя</param>
        /// <response code="201">Событие успешно создано</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/events/user")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateUserEvent")]
        [SwaggerResponse(statusCode: 201, type: typeof(EventResponse), description: "Событие успешно создано")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateUserEvent([FromBody] UserEvent userEvent)
        {

            userEvent.Status = "success";
            return new ObjectResult(userEvent)
                            {
                                StatusCode = 201
                            }; //Created($"/api/payments/{payment.Id}", payment);
        }
        
            /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/events/payment")]
        [ValidateModelState]
        [SwaggerOperation("GetAllPayments")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Payment>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllPayments([FromQuery(Name = "user_id")] int? userId)
        {
            try
            {
                _logger.LogInformation("Reading payment events from Kafka...");
                
                // Читаем события из Kafka
                var paymentEventsJson = _kafkaReader.ReadPaymentEvents(maxMessages: 50);
                var paymentEvents = new List<PaymentEvent>();

                foreach (var eventJson in paymentEventsJson)
                {
                    try
                    {
                        var paymentEvent = JsonConvert.DeserializeObject<KafkaEvent>(eventJson);
                        if (paymentEvent != null)
                        {
                            // Фильтрация по user_id если указан
                            if (userId == null || paymentEvent.Payload.UserId == userId)
                            {
                                paymentEvents.Add(paymentEvent.Payload);
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogWarning(ex, "Failed to deserialize payment event: {EventJson}", eventJson);
                    }
                }

                _logger.LogInformation("Returning {Count} payment events", paymentEvents.Count);
                return new ObjectResult(paymentEvents);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to read payment events from Kafka");
                return StatusCode(500, new Error { VarError = "Failed to read payment events" });
            }
        }
    
    }
}
