/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class HealthApiController : ControllerBase
    { 
        /// <summary>
        /// Проверка работоспособности микросервиса событий
        /// </summary>
        /// <remarks>Возвращает статус работоспособности микросервиса событий</remarks>
        /// <response code="200">Успешный ответ</response>
        [HttpGet]
        [Route("/api/events/health")]
        [ValidateModelState]
        [SwaggerOperation("GetEventsServiceHealth")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetMoviesServiceHealth200Response), description: "Успешный ответ")]
        public virtual IActionResult GetEventsServiceHealth()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\n  \"status\" : true\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GetMoviesServiceHealth200Response>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Проверка работоспособности микросервиса фильмов
        /// </summary>
        /// <remarks>Возвращает статус работоспособности микросервиса фильмов</remarks>
        /// <response code="200">Успешный ответ</response>
        [HttpGet]
        [Route("/api/movies/health")]
        [ValidateModelState]
        [SwaggerOperation("GetMoviesServiceHealth")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetMoviesServiceHealth200Response), description: "Успешный ответ")]
        public virtual IActionResult GetMoviesServiceHealth()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\n  \"status\" : true\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GetMoviesServiceHealth200Response>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Проверка работоспособности API Gateway
        /// </summary>
        /// <remarks>Возвращает статус работоспособности прокси-сервиса</remarks>
        /// <response code="200">Успешный ответ</response>
        [HttpGet]
        [Route("/health")]
        [ValidateModelState]
        [SwaggerOperation("GetProxyHealth")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Успешный ответ")]
        public virtual IActionResult GetProxyHealth()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
