/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class MoviesApiController : ControllerBase
    { 
        /// <summary>
        /// Создание нового фильма
        /// </summary>
        /// <remarks>Добавляет новый фильм в систему</remarks>
        /// <param name="movieInput">Данные фильма для создания</param>
        /// <response code="201">Фильм успешно создан</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/movies")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateMovie")]
        [SwaggerResponse(statusCode: 201, type: typeof(Movie), description: "Фильм успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateMovie([FromBody]MovieInput movieInput)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"genres\" : [ \"Sci-Fi\", \"Action\", \"Thriller\" ],\n  \"rating\" : 8.8,\n  \"description\" : \"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.\",\n  \"id\" : 1,\n  \"title\" : \"Inception\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Movie>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Получение списка всех фильмов
        /// </summary>
        /// <remarks>Возвращает список всех фильмов с их метаданными</remarks>
        /// <response code="200">Успешный ответ</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/movies")]
        [ValidateModelState]
        [SwaggerOperation("GetAllMovies")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Movie>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllMovies()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "[ {\n  \"genres\" : [ \"Sci-Fi\", \"Action\", \"Thriller\" ],\n  \"rating\" : 8.8,\n  \"description\" : \"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.\",\n  \"id\" : 1,\n  \"title\" : \"Inception\"\n}, {\n  \"genres\" : [ \"Sci-Fi\", \"Action\", \"Thriller\" ],\n  \"rating\" : 8.8,\n  \"description\" : \"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.\",\n  \"id\" : 1,\n  \"title\" : \"Inception\"\n} ]";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Movie>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
