/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentsApiController : ControllerBase
    { 

        private readonly IKafkaEventPublisher _kafka;
        private readonly ILogger<PaymentsApiController> _logger;

        public PaymentsApiController(IKafkaEventPublisher kafka, ILogger<PaymentsApiController> logger)
        {
            _kafka = kafka;
            _logger = logger;
        }
        /// <summary>
        /// Создание нового платежа
        /// </summary>
        /// <remarks>Регистрирует новый платеж в системе</remarks>
        /// <param name="paymentInput">Данные платежа для создания</param>
        /// <response code="201">Платеж успешно создан</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/payments")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreatePayment")]
        [SwaggerResponse(statusCode: 201, type: typeof(Payment), description: "Платеж успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual async Task<IActionResult> CreatePayment([FromBody]PaymentInput paymentInput)
        {

            try
            {
                // Генерируем уникальный ID платежа (в реальности — из БД или ID-сервиса)
                var paymentId = Random.Shared.Next(1000, 999999);
                var timestamp = DateTime.UtcNow;

                // Формируем Payment для ответа
                var payment = new Payment
                {
                    Id = paymentId,
                    UserId = paymentInput.UserId,
                    Amount = paymentInput.Amount,
                    Timestamp = timestamp
                };

                // Формируем событие платежа
                var paymentEvent = new PaymentEvent
                {
                    PaymentId = payment.Id,
                    UserId = payment.UserId,
                    Amount = payment.Amount,
                    Status = "completed",
                    Timestamp = payment.Timestamp
                };

                // Публикуем событие в Kafka
                var eventId = Guid.NewGuid().ToString();
                var @event = new Event
                {
                    Id = eventId,
                    Type = "payment",
                    Timestamp = timestamp,
                    Payload = paymentEvent
                };

                var eventData = JsonConvert.SerializeObject(@event);
                await _kafka.PublishAsync("cinema.events", eventId, eventData);

                _logger.LogInformation("Published payment event: {EventId} for payment {PaymentId}", eventId, payment.Id);

                // Возвращаем 201 Created
                return CreatedAtRoute("GetPaymentById", new { id = payment.Id }, payment);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to create payment or publish event");
                return StatusCode(500, new Error {  VarError = "Internal Server Error" });
            }
        }

       /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/payments")]
        [ValidateModelState]
        [SwaggerOperation("GetAllPayments")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Payment>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllPayments([FromQuery(Name = "user_id")] int? userId)
        {
            // В микросервисе событий нет хранилища платежей → возвращаем пустой список
            // (либо можно вернуть ошибку 404/501, но по спецификации ожидается 200)
            return Ok(new List<Payment>());
        }
    }
}
