/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentsApiController : ControllerBase
    { 
        /// <summary>
        /// Создание нового платежа
        /// </summary>
        /// <remarks>Регистрирует новый платеж в системе</remarks>
        /// <param name="paymentInput">Данные платежа для создания</param>
        /// <response code="201">Платеж успешно создан</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/payments")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreatePayment")]
        [SwaggerResponse(statusCode: 201, type: typeof(Payment), description: "Платеж успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreatePayment([FromBody]PaymentInput paymentInput)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"amount\" : 9.99,\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"timestamp\" : \"2023-01-15T14:30:00Z\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Payment>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Получение списка всех платежей
        /// </summary>
        /// <remarks>Возвращает список всех платежей в системе</remarks>
        /// <param name="userId">ID пользователя для фильтрации платежей</param>
        /// <response code="200">Успешный ответ</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/payments")]
        [ValidateModelState]
        [SwaggerOperation("GetAllPayments")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Payment>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllPayments([FromQuery (Name = "user_id")]int? userId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "[ {\n  \"amount\" : 9.99,\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"timestamp\" : \"2023-01-15T14:30:00Z\"\n}, {\n  \"amount\" : 9.99,\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"timestamp\" : \"2023-01-15T14:30:00Z\"\n} ]";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Payment>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
