/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentsApiController : ControllerBase
    { 
        private readonly IKafkaEventPublisher _kafka;
        private readonly IKafkaEventReader _kafkaReader;
        private readonly ILogger<PaymentsApiController> _logger;

        public PaymentsApiController(
            IKafkaEventPublisher kafka,
            IKafkaEventReader kafkaReader,
            ILogger<PaymentsApiController> logger)
        {
            _kafka = kafka;
            _kafkaReader = kafkaReader;
            _logger = logger;
        }
    
        /// <summary>
        /// Создание нового платежа
        /// </summary>
        /// <remarks>Регистрирует новый платеж в системе</remarks>
        /// <param name="paymentInput">Данные платежа для создания</param>
        /// <response code="201">Платеж успешно создан</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/payments")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreatePayment")]
        [SwaggerResponse(statusCode: 201, type: typeof(Payment), description: "Платеж успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreatePayment([FromBody]PaymentInput paymentInput)
        {

            try
            {
                _logger.LogInformation("Entered CreatePayment");
                Console.WriteLine("=== 1 ===");

                // Генерируем уникальный ID платежа (в реальности — из БД или ID-сервиса)
                var paymentId = Random.Shared.Next(1000, 999999);
                var timestamp = DateTime.UtcNow;

                // Формируем Payment для ответа
                var payment = new Payment
                {
                    Id = paymentId,
                    UserId = paymentInput.UserId,
                    Amount = paymentInput.Amount,
                    Timestamp = timestamp
                };

                // Формируем событие платежа
                var paymentEvent = new PaymentEvent
                {
                    PaymentId = payment.Id,
                    UserId = payment.UserId,
                    Amount = payment.Amount,
                    Status = "completed",
                    Timestamp = payment.Timestamp
                };

                // Публикуем событие в Kafka
                var eventId = Guid.NewGuid().ToString();
                var @event = new Event
                {
                    Id = eventId,
                    Type = "payment",
                    Timestamp = timestamp,
                    Payload = paymentEvent
                };

                Console.WriteLine("=== 2 ===");
                var eventData = JsonConvert.SerializeObject(@event);
                _kafka.PublishAsync("payment-events", eventId, eventData);
                throw new Exception("ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss");
                _logger.LogInformation("Published payment event: {EventId} for payment {PaymentId}", eventId, payment.Id);
                _logger.LogInformation("й1");
                Console.WriteLine("=== 3 ===");
                throw new Exception("sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss");
                return new ObjectResult(payment)
                            {
                                StatusCode = 201
                            }; //Created($"/api/payments/{payment.Id}", payment);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to create payment or publish event");
                return StatusCode(500, new Error {  VarError = "Internal Server Error" });
            }
        }

       /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/payments")]
        [ValidateModelState]
        [SwaggerOperation("GetAllPayments")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Payment>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllPayments([FromQuery(Name = "user_id")] int? userId)
        {
            try
            {
                _logger.LogInformation("Reading payment events from Kafka...");
                
                // Читаем события из Kafka
                var paymentEventsJson = _kafkaReader.ReadPaymentEvents(maxMessages: 50);
                var paymentEvents = new List<PaymentEvent>();

                foreach (var eventJson in paymentEventsJson)
                {
                    try
                    {
                        var paymentEvent = JsonConvert.DeserializeObject<KafkaEvent>(eventJson);
                        if (paymentEvent != null)
                        {
                            // Фильтрация по user_id если указан
                            if (userId == null || paymentEvent.Payload.UserId == userId)
                            {
                                paymentEvents.Add(paymentEvent.Payload);
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogWarning(ex, "Failed to deserialize payment event: {EventJson}", eventJson);
                    }
                }

                _logger.LogInformation("Returning {Count} payment events", paymentEvents.Count);
                return new ObjectResult(paymentEvents);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to read payment events from Kafka");
                return StatusCode(500, new Error { VarError = "Failed to read payment events" });
            }
        }
    }
}
