/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Cinema.Events.Attributes;
using Cinema.Events.Models;

namespace Cinema.Events.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SubscriptionsApiController : ControllerBase
    { 
        /// <summary>
        /// Создание новой подписки
        /// </summary>
        /// <remarks>Регистрирует новую подписку в системе</remarks>
        /// <param name="subscriptionInput">Данные подписки для создания</param>
        /// <response code="201">Подписка успешно создана</response>
        /// <response code="400">Некорректный запрос</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/api/subscriptions")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateSubscription")]
        [SwaggerResponse(statusCode: 201, type: typeof(Subscription), description: "Подписка успешно создана")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректный запрос")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult CreateSubscription([FromBody]SubscriptionInput subscriptionInput)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\n  \"end_date\" : \"2023-12-31T23:59:59Z\",\n  \"plan_type\" : \"premium\",\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"start_date\" : \"2023-01-01T00:00:00Z\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Subscription>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Получение списка всех подписок
        /// </summary>
        /// <remarks>Возвращает список всех подписок в системе</remarks>
        /// <param name="userId">ID пользователя для фильтрации подписок</param>
        /// <response code="200">Успешный ответ</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpGet]
        [Route("/api/subscriptions")]
        [ValidateModelState]
        [SwaggerOperation("GetAllSubscriptions")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Subscription>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервера")]
        public virtual IActionResult GetAllSubscriptions([FromQuery (Name = "user_id")]int? userId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "[ {\n  \"end_date\" : \"2023-12-31T23:59:59Z\",\n  \"plan_type\" : \"premium\",\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"start_date\" : \"2023-01-01T00:00:00Z\"\n}, {\n  \"end_date\" : \"2023-12-31T23:59:59Z\",\n  \"plan_type\" : \"premium\",\n  \"user_id\" : 1,\n  \"id\" : 1,\n  \"start_date\" : \"2023-01-01T00:00:00Z\"\n} ]";
            exampleJson = "{\n  \"error\" : \"Internal Server Error\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Subscription>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
