/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Cinema.Events.Converters;

namespace Cinema.Events.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MovieInput : IEquatable<MovieInput>
    {
        /// <summary>
        /// Название фильма
        /// </summary>
        /// <value>Название фильма</value>
        /* <example>Inception</example> */
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Описание фильма
        /// </summary>
        /// <value>Описание фильма</value>
        /* <example>A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.</example> */
        [Required]
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Жанры фильма
        /// </summary>
        /// <value>Жанры фильма</value>
        /* <example>[&quot;Sci-Fi&quot;,&quot;Action&quot;,&quot;Thriller&quot;]</example> */
        [DataMember(Name="genres", EmitDefaultValue=false)]
        public List<string> Genres { get; set; }

        /// <summary>
        /// Рейтинг фильма
        /// </summary>
        /// <value>Рейтинг фильма</value>
        /* <example>8.8</example> */
        [Required]
        [DataMember(Name="rating", EmitDefaultValue=true)]
        public float Rating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MovieInput {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Genres: ").Append(Genres).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MovieInput)obj);
        }

        /// <summary>
        /// Returns true if MovieInput instances are equal
        /// </summary>
        /// <param name="other">Instance of MovieInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MovieInput other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Genres == other.Genres ||
                    Genres != null &&
                    other.Genres != null &&
                    Genres.SequenceEqual(other.Genres)
                ) && 
                (
                    Rating == other.Rating ||
                    
                    Rating.Equals(other.Rating)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Genres != null)
                    hashCode = hashCode * 59 + Genres.GetHashCode();
                    
                    hashCode = hashCode * 59 + Rating.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MovieInput left, MovieInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MovieInput left, MovieInput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
