/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Cinema.Events.Converters;

namespace Cinema.Events.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MovieEvent : IEquatable<MovieEvent>
    {
        /// <summary>
        /// Идентификатор фильма
        /// </summary>
        /// <value>Идентификатор фильма</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="movie_id", EmitDefaultValue=true)]
        public int MovieId { get; set; }

        /// <summary>
        /// Название фильма
        /// </summary>
        /// <value>Название фильма</value>
        /* <example>Inception</example> */
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Действие с фильмом
        /// </summary>
        /// <value>Действие с фильмом</value>
        /* <example>viewed</example> */
        [Required]
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// Идентификатор пользователя (опционально)
        /// </summary>
        /// <value>Идентификатор пользователя (опционально)</value>
        /* <example>1</example> */
        [DataMember(Name="user_id", EmitDefaultValue=true)]
        public int UserId { get; set; }

        /// <summary>
        /// Рейтинг (опционально)
        /// </summary>
        /// <value>Рейтинг (опционально)</value>
        /* <example>8.5</example> */
        [DataMember(Name = "rating", EmitDefaultValue = true)]
        public float Rating { get; set; }
        
        /// <summary>
        /// Статус 
        /// </summary>
        /// <value>Статус </value>
        /* <example>completed</example> */

        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Жанры фильма (опционально)
        /// </summary>
        /// <value>Жанры фильма (опционально)</value>
        /* <example>[&quot;Sci-Fi&quot;,&quot;Action&quot;]</example> */
        [DataMember(Name="genres", EmitDefaultValue=false)]
        public List<string> Genres { get; set; }

        /// <summary>
        /// Описание фильма (опционально)
        /// </summary>
        /// <value>Описание фильма (опционально)</value>
        /* <example>A mind-bending thriller</example> */
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MovieEvent {\n");
            sb.Append("  MovieId: ").Append(MovieId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("  Genres: ").Append(Genres).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MovieEvent)obj);
        }

        /// <summary>
        /// Returns true if MovieEvent instances are equal
        /// </summary>
        /// <param name="other">Instance of MovieEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MovieEvent other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MovieId == other.MovieId ||
                    
                    MovieId.Equals(other.MovieId)
                ) && 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Action == other.Action ||
                    Action != null &&
                    Action.Equals(other.Action)
                ) && 
                (
                    UserId == other.UserId ||
                    
                    UserId.Equals(other.UserId)
                ) && 
                (
                    Rating == other.Rating ||
                    
                    Rating.Equals(other.Rating)
                ) && 
                (
                    Genres == other.Genres ||
                    Genres != null &&
                    other.Genres != null &&
                    Genres.SequenceEqual(other.Genres)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MovieId.GetHashCode();
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Action != null)
                    hashCode = hashCode * 59 + Action.GetHashCode();
                    
                    hashCode = hashCode * 59 + UserId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Rating.GetHashCode();
                    if (Genres != null)
                    hashCode = hashCode * 59 + Genres.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MovieEvent left, MovieEvent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MovieEvent left, MovieEvent right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
