/*
 * CinemaAbyss API
 *
 * API спецификация для системы CinemaAbyss, включающая монолит и микросервисы.  Система CinemaAbyss представляет собой платформу для управления фильмами, пользователями, платежами и подписками. Архитектура системы включает монолитное приложение и выделенные микросервисы. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cinemaabyss.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Cinema.Events.Converters;

namespace Cinema.Events.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentEvent : IEquatable<PaymentEvent>
    {
        /// <summary>
        /// Идентификатор платежа
        /// </summary>
        /// <value>Идентификатор платежа</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name = "payment_id", EmitDefaultValue = true)]
        public int PaymentId { get; set; }

        /// <summary>
        /// Идентификатор пользователя
        /// </summary>
        /// <value>Идентификатор пользователя</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name = "user_id", EmitDefaultValue = true)]
        public int UserId { get; set; }

        /// <summary>
        /// Сумма платежа
        /// </summary>
        /// <value>Сумма платежа</value>
        /* <example>9.99</example> */
        [Required]
        [DataMember(Name = "amount", EmitDefaultValue = true)]
        public float Amount { get; set; }

        /// <summary>
        /// Статус платежа
        /// </summary>
        /// <value>Статус платежа</value>
        /* <example>completed</example> */
        [Required]
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Время платежа
        /// </summary>
        /// <value>Время платежа</value>
        /* <example>2023-01-15T14:30Z</example> */
        [Required]
        [DataMember(Name = "timestamp", EmitDefaultValue = true)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Тип метода оплаты (опционально)
        /// </summary>
        /// <value>Тип метода оплаты (опционально)</value>
        /* <example>credit_card</example> */
        [DataMember(Name = "method_type", EmitDefaultValue = false)]
        public string MethodType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentEvent {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  MethodType: ").Append(MethodType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentEvent)obj);
        }

        /// <summary>
        /// Returns true if PaymentEvent instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentEvent other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PaymentId == other.PaymentId ||

                    PaymentId.Equals(other.PaymentId)
                ) &&
                (
                    UserId == other.UserId ||

                    UserId.Equals(other.UserId)
                ) &&
                (
                    Amount == other.Amount ||

                    Amount.Equals(other.Amount)
                ) &&
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) &&
                (
                    Timestamp == other.Timestamp ||

                    Timestamp.Equals(other.Timestamp)
                ) &&
                (
                    MethodType == other.MethodType ||
                    MethodType != null &&
                    MethodType.Equals(other.MethodType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + PaymentId.GetHashCode();

                hashCode = hashCode * 59 + UserId.GetHashCode();

                hashCode = hashCode * 59 + Amount.GetHashCode();
                if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();

                hashCode = hashCode * 59 + Timestamp.GetHashCode();
                if (MethodType != null)
                    hashCode = hashCode * 59 + MethodType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PaymentEvent left, PaymentEvent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentEvent left, PaymentEvent right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
    
    [DataContract]
    public class KafkaEvent
    {
        [JsonProperty("id")]
        public string Id { get; set; }
        
        [JsonProperty("type")]
        public string Type { get; set; }
        
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; }
        
        [JsonProperty("payload")]
        public PaymentEvent Payload { get; set; }
    }
}
