# Events service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monolith-cb
  namespace: cinemaabyss
spec:
  host: monolith.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
---
# Movies service  
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-service-cb
  namespace: cinemaabyss
spec:
  host: movies-service.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
      http:
        http1MaxPendingRequests: 20
        maxRequestsPerConnection: 20
    outlierDetection:
      consecutive5xxErrors: 3
      consecutiveGatewayErrors: 2
      interval: 15s
      baseEjectionTime: 60s
      maxEjectionPercent: 50