:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore .\Cinema.Events
dotnet build .\Cinema.Events
echo Now, run the following to start the project: dotnet run -p .\Cinema.Events\Cinema.Events.csproj --launch-profile web.
echo.
